# Generated by Django 5.1.2 on 2024-10-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
